# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Awe 
email: 1208484996@qq.com
description: > # this means to ignore newlines until "baseurl:"
  这是一个个人博客，用于记录生活和学习的点点滴滴。
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dlrandy.github.io/AWE/" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  DLRandy

# Build settings
markdown: kramdown
